variables:
  COUCHDB_USER: couchdb
  COUCHDB_PASSWORD: mypassword
  DEV_IMAGE: zombieguru/godhand:$CI_BUILD_REF_NAME
  RELEASE_IMAGE: zombieguru/godhand:latest

.docker-job: &docker_base
  image: docker:git
  services:
    - docker:dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD -e $DOCKER_EMAIL

stages:
  - build
  - test
  - deploy

build:
  <<: *docker_base
  stage: build
  script:
    - docker build -t $DEV_IMAGE .
    - docker push $DEV_IMAGE

flake8:
  stage: test
  image: python:3.4-alpine
  services: []
  before_script: []
  script:
    - pip3 install flake8
    - flake8

nosetests:
  stage: test
  image: $DEV_IMAGE
  services:
    - couchdb:latest
  variables:
    TEST_GODHAND_COUCHDB_URL: http://$COUCHDB_USER:$COUCHDB_PASSWORD@couchdb:5984
  script:
    - nosetests --with-coverage --cover-package godhand -v godhand

deploy:
  <<: *docker_base
  stage: deploy
  script:
    - docker pull $DEV_IMAGE
    - docker tag $DEV_IMAGE $RELEASE_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
